"""Initial schema for notebook architecture

Revision ID: cd1227a8d5da
Revises: 
Create Date: 2025-12-11 22:15:09.953065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd1227a8d5da'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('last_active', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('notebooks',
    sa.Column('notebook_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('document_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notebook_id')
    )
    op.create_index('idx_user_notebooks', 'notebooks', ['user_id', 'created_at'], unique=False)
    op.create_table('conversations',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('notebook_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['notebook_id'], ['notebooks.notebook_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('conversation_id')
    )
    op.create_index('idx_notebook_conversations', 'conversations', ['notebook_id', 'timestamp'], unique=False)
    op.create_index('idx_user_conversations', 'conversations', ['user_id', 'timestamp'], unique=False)
    op.create_table('notebook_sources',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('notebook_id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=True),
    sa.Column('upload_timestamp', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['notebook_id'], ['notebooks.notebook_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('source_id')
    )
    op.create_index('idx_notebook_sources', 'notebook_sources', ['notebook_id', 'upload_timestamp'], unique=False)
    op.create_index('idx_source_hash', 'notebook_sources', ['notebook_id', 'file_hash'], unique=True)
    op.create_table('query_logs',
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('notebook_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['notebook_id'], ['notebooks.notebook_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index('idx_query_logs_notebook', 'query_logs', ['notebook_id', 'timestamp'], unique=False)
    op.create_index('idx_query_logs_timestamp', 'query_logs', ['timestamp'], unique=False)
    op.create_index('idx_query_logs_user', 'query_logs', ['user_id', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_query_logs_user', table_name='query_logs')
    op.drop_index('idx_query_logs_timestamp', table_name='query_logs')
    op.drop_index('idx_query_logs_notebook', table_name='query_logs')
    op.drop_table('query_logs')
    op.drop_index('idx_source_hash', table_name='notebook_sources')
    op.drop_index('idx_notebook_sources', table_name='notebook_sources')
    op.drop_table('notebook_sources')
    op.drop_index('idx_user_conversations', table_name='conversations')
    op.drop_index('idx_notebook_conversations', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index('idx_user_notebooks', table_name='notebooks')
    op.drop_table('notebooks')
    op.drop_table('users')
    # ### end Alembic commands ###
