"""Type definitions for Analytics module.

Based on ANALYTICS_DATA_FLOW.md specifications.
"""

from typing import TypedDict, Optional, List, Any, Literal
from datetime import datetime


# Data Types
DataType = Literal["numeric", "categorical", "datetime", "boolean", "text"]
AggregationType = Literal["sum", "avg", "count", "min", "max", "median"]
ChartType = Literal["bar", "line", "pie", "scatter", "area"]
FilterType = Literal["categorical", "range", "date"]


class ColumnStatistics(TypedDict, total=False):
    """Statistical summary for numeric columns."""
    mean: float
    median: float
    std: float
    min: float
    max: float
    skewness: float
    kurtosis: float
    quartiles: List[float]  # [Q1, Q2, Q3]
    iqr: float


class CategoricalStats(TypedDict, total=False):
    """Statistics for categorical columns."""
    unique_count: int
    top_values: List[dict]  # [{value, count, percent}]
    entropy: float


class ColumnMetadata(TypedDict):
    """Metadata for a single column in the dataset."""
    name: str
    inferred_type: DataType
    unique_count: int
    null_count: int
    null_percent: float
    sample_values: List[Any]
    statistics: Optional[ColumnStatistics]
    categorical: Optional[CategoricalStats]


class ParsedData(TypedDict):
    """Result of parsing an Excel/CSV file."""
    data: List[dict]  # Row data as list of dicts
    columns: List[ColumnMetadata]
    row_count: int
    column_count: int
    sample_data: List[dict]  # First N rows for LLM
    file_name: str
    file_size: int
    parsing_errors: List[dict]


class CorrelationInfo(TypedDict):
    """High correlation information."""
    var1: str
    var2: str
    correlation: float


class QualityAlert(TypedDict):
    """Data quality alert."""
    column: Optional[str]
    severity: Literal["critical", "warning", "info"]
    alert_type: str
    message: str
    recommendation: Optional[str]


class ProfilingResult(TypedDict):
    """Result from ydata-profiling analysis."""
    overview: dict  # Summary statistics
    columns: List[ColumnMetadata]
    correlations: List[CorrelationInfo]
    quality_alerts: List[QualityAlert]
    quality_score: float  # 0-10
    html_report: Optional[str]  # Path to HTML report
    profile_json: Optional[dict]  # Raw profile data


class KPIConfig(TypedDict, total=False):
    """Configuration for a KPI card."""
    id: str
    title: str
    metric: str  # Column name
    aggregation: AggregationType
    format: Literal["number", "currency", "percentage"]
    icon: Optional[str]  # Lucide icon name
    color: Optional[Literal["blue", "green", "red", "purple", "orange"]]
    prefix: Optional[str]  # e.g., "$"
    suffix: Optional[str]  # e.g., "%"
    decimal_places: Optional[int]


class ChartConfig(TypedDict, total=False):
    """Configuration for a chart visualization."""
    id: str
    title: str
    type: ChartType
    x_axis: str  # Column name
    y_axis: str  # Column name or expression
    aggregation: Optional[AggregationType]
    color: Optional[str]
    allow_cross_filter: Optional[bool]
    sort_by: Optional[Literal["value", "label"]]
    sort_order: Optional[Literal["asc", "desc"]]
    limit: Optional[int]  # Top N items


class FilterConfig(TypedDict, total=False):
    """Configuration for a filter control."""
    id: str
    column: str
    type: FilterType
    label: str
    default_value: Optional[Any]
    options: Optional[List[str]]  # For categorical
    min_value: Optional[float]  # For range
    max_value: Optional[float]  # For range


class DashboardMetadata(TypedDict, total=False):
    """Metadata about the generated dashboard."""
    title: str
    description: str
    recommendation_reason: Optional[str]
    generated_at: Optional[str]
    data_source: Optional[str]


class DashboardConfig(TypedDict):
    """Complete dashboard configuration generated by LLM."""
    kpis: List[KPIConfig]
    charts: List[ChartConfig]
    filters: List[FilterConfig]
    metadata: DashboardMetadata


class ModificationResult(TypedDict, total=False):
    """Result of a dashboard modification."""
    success: bool
    dashboard_config: Optional[DashboardConfig]
    changes: List[str]  # List of changes made
    error: Optional[str]
    can_undo: bool
    can_redo: bool


class AnalysisSession(TypedDict, total=False):
    """Analytics session state."""
    session_id: str
    user_id: str
    notebook_id: Optional[str]
    file_name: str
    file_path: str
    file_size: int
    status: Literal["uploaded", "parsing", "profiling", "analyzing", "complete", "error"]
    created_at: str
    updated_at: Optional[str]
    parsed_data: Optional[ParsedData]
    profiling_result: Optional[ProfilingResult]
    dashboard_config: Optional[DashboardConfig]
    error_message: Optional[str]
    progress: int  # 0-100

    # NLP-driven analytics agent fields
    initial_requirements: Optional[str]  # User's initial dashboard requirements
    generation_prompt: Optional[str]  # Full prompt used for initial generation
    modification_history: List[DashboardConfig]  # Stack for undo
    redo_stack: List[DashboardConfig]  # Stack for redo
    last_changes: List[str]  # Last changes made by modification
